version: '3.4'

services:
  hub:
    image: selenium/hub:3

  firefox:
    image: selenium/${SELENIUM_FIREFOX_IMAGE:-node-firefox}:3
    ports:
      - 5900
    volumes:
      - /dev/shm:/dev/shm
    environment:
      HUB_HOST: hub
    depends_on:
      - hub

  chrome:
    image: selenium/${SELENIUM_CHROME_IMAGE:-node-chrome}:3
    ports:
      - 5900
    volumes:
      - /dev/shm:/dev/shm
    environment:
      HUB_HOST: hub
    depends_on:
      - hub

  webapp:
    image: ${DIST_IMAGE}

  npm:
    image: ${TEST_IMAGE}
    entrypoint: npm
    volumes:
      - reports:/usr/src/app/reports

  protractor:
    image: ${TEST_IMAGE}
    command: ./bin/wait-for-hub npm run ${NPM_SCRIPT:-e2e-ci}
    environment:
      - GIT_COMMIT_SHA=${GIT_COMMIT_SHA:-null}
    depends_on:
      - hub
      - webapp
    volumes:
      - reports:/usr/src/app/reports

  allure:
    image: mattupstate/allure
    environment:
      - ALLURE_ENVIRONMENT
    volumes:
      - reports:/usr/src/allure

  aws:
    image: mesosphere/aws-cli
    environment:
      - AWS_DEFAULT_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    working_dir: /work
    volumes:
      - reports:/work

volumes:
   reports:
