version: '3.4'

services:
  hub:
    image: selenium/hub:3

  firefox:
    image: selenium/${SELENIUM_FIREFOX_IMAGE}:3
    ports:
      - 5900
    volumes:
      - /dev/shm:/dev/shm
    environment:
      HUB_HOST: hub
    depends_on:
      - hub

  chrome:
    image: selenium/${SELENIUM_CHROME_IMAGE}:3
    ports:
      - 5900
    volumes:
      - /dev/shm:/dev/shm
    environment:
      HUB_HOST: hub
    depends_on:
      - hub

  webapp:
    image: ${DIST_IMAGE}

  protractor:
    image: ${TEST_IMAGE}
    command: ./bin/wait-for-hub npm run ${NPM_SCRIPT:-e2e-ci}
    volumes:
      - ${LOCAL_E2E_REPORTS_DIR}:${DOCKER_E2E_REPORTS_DIR}
    environment:
      - GIT_COMMIT_SHA=${GIT_COMMIT_SHA:-null}
    depends_on:
      - hub
      - webapp
