steps:
  - command: "make test-image dist-image"
    label: ":docker: Images"
  - wait
  - command: "make test"
    label: ":angular: Test"
  - command: "make analysis"
    label: ":eslint: Analysis"
  - command: "make audit"
    label: ":nodesecurity: Audit"
  - command: "make e2e"
    label: ":protractor: End-to-End"
  - command: "make release-plan"
    label: ":terraform: Infra Plan"
